"""Enable vector embeddings

Revision ID: 14b3fffd1053
Revises: 8f2925d6a8ad
Create Date: 2025-09-23 23:41:40.807641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b3fffd1053'
down_revision = '8f2925d6a8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('title_embedding',
               existing_type=sa.TEXT(),
               type_=pgvector.sqlalchemy.Vector(dim=384),
               existing_nullable=True)
        batch_op.alter_column('content_embedding',
               existing_type=sa.TEXT(),
               type_=pgvector.sqlalchemy.Vector(dim=384),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('content_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=384),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=384),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
